#cordova platform add android
#cordova platform add firefoxos
#cordova platform add ios
cordova plugin add org.apache.cordova.console
cordova plugin add org.apache.cordova.device
cordova plugin add org.apache.cordova.dialogs
cordova plugin add org.apache.cordova.vibration
cordova plugin add org.apache.cordova.network-information
cordova plugin add de.appplant.cordova.plugin.background-mode
cordova plugin add de.appplant.cordova.plugin.local-notification
cordova plugin add com.jamiestarke.webviewdebug
